### ISSUE TITLE
Plugin name argument unnecessary

### ISSUE THREAD

**Issue by toolmantim** [buildkite-plugins/buildkite-plugin-linter#15]
Tt should be unnecessary to configure the linter with `--name` just so it can search the readme for `plugins: ${name}#v.*` code blocks, because it's already set in the plugin.yml file. It'll need to handle the org scoping tho, which is currently done via the `--name` linter argument.

**Comment by toolmantim** [comment]
This does assume though that the `name` in plugin.yml matches the repo name. So it wouldn't allow for the name to be `Docker Compose` for example.

These are the current names of the plugins (some wouldn't validate):

* artifacts: artifacts
* calibre: Calibre
* detect-clowns: detect-clowns
* docker: docker
* docker-compose: docker-compose
* docker-login: Docker Login
* ecr: ECR
* ecs-deploy: ecs-deploy
* golang-build: golang-build
* gopath-checkout: gopath-checkout
* junit-annotate: junit-annotate
* plugin-linter: plugin-linter
* shellcheck: Shellcheck
* slurm: slurm

**Comment by toolmantim** [comment]
@keithpitt @lox reckon we standardise on having the plugin.yml `name` entry match the repo slug, as per the community plugins and most of our plugins, or go for Plain English Names?

Whatever one we choose, people will follow by example, which is I think what's happened so far.

If we go with plain English ones, I'll change the plugin-linter's `--name` argument to `--id` instead, or whatever we call the `my-org/my-`plugin` part of `my-org/my-plugin#v1`?

**Comment by toolmantim** [comment]
Unrelated: it'd be great to add `tags` or `topics` to the plugin.yml, so in the future we can slice and browse plugins by tags

**Comment by toolmantim** [comment]
https://probot.github.io/apps/ is a nice example of a simple plugin directory. I'm 99% certain we want plain English for the `name` field in plugin.yml now.

**Comment by keithpitt** [comment]
@toolmantim yeah, I agree. I think plugin `id` is a good differentiator. I wouldn't want repo name to == plugin name since you'd get into all sorts of issues with repo name changes, and repos with multiple plugins in them.

**Comment by toolmantim** [comment]
Alright, all of our own plugins have been updated. 

PRs have been sent for some of the community plugins:

* cultureamp/aws-assume-role-buildkite-plugin#3
* bugcrowd/test-summary-buildkite-plugin#14
* jobready/codeclimate-test-reporter-buildkite-plugin#5

Still to come:

* https://github.com/joscha/sauce-connect-buildkite-plugin
* https://github.com/thedyrt/skip-checkout-buildkite-plugin
* https://github.com/thedyrt/git-commit-buildkite-plugin
* https://github.com/thedyrt/change-directory-buildkite-plugin

**Comment by toolmantim** [comment]
Ok, all done!
