### ISSUE TITLE
README version checking is too strict

### ISSUE THREAD

**Issue by extemporalgenome** [buildkite-plugins/buildkite-plugin-linter#25]
The README version checking algorithm creates a chicken-and-egg situation that may be problematic for some build processes. In particular, because it requires that the version is exactly the latest semver tag, unless the master build process (after PR merge) produces a new version and updates the README, or each commit within a PR is given the release semver, then either the PR build will fail or the master build will fail.

A flag should be provided to allow PRs to use a newer-than-latest semver in the README examples (changing the check to greater-or-equals instead of just equals).

**Comment by toolmantim** [comment]
Thanks for the feedback! I was waiting for this feedback, because the current implementation is way too simple/naïve. Sorry if it’s caused you hassle.

What do you reckon the best algorithm is? I’ve been wondering too, given tags are often created after the commit is pushed.

**Comment by toolmantim** [comment]
I've changed it to a greater than or equals now! Thanks for the feedback.
