### ISSUE TITLE
Runtime linting

### ISSUE THREAD

**Issue by benquinteros** [buildkite-plugins/buildkite-plugin-linter#467]
Would be nice if we could pass the runtime configuration yaml and the plugin schema yaml to the linter in say a hook to validate if the correct configuration schema was passed. We currently have to validate this in the plugin itself. Or is there already a solution for this?

**Comment by toote** [comment]
That can not be implemented in the linter because it is not part of the normal execution path in a normal step or plugin.

But it is such a good idea that it is [already implemented in the agent (but turned off by default)](https://buildkite.com/docs/agent/v3/configuration#no-plugin-validation)

**Comment by benquinteros** [comment]
Thank you
